/* ============================================================
   codegen.h — Pseudo-Assembly Code Generator
   Compiler Construction Visualizer Project

   Phase 8: Target Code Generation
   ---------------------------------
   The final phase translates TAC into pseudo-assembly code
   resembling x86 / MIPS-style mnemonics.

   Mapping:
     TAC: t1 = a + b      →   MOV  R0, a
                               ADD  R0, b
                               MOV  t1, R0

     TAC: a = t1          →   MOV  a, t1
     TAC: ifFalse t goto L →  CMP  t, 0
                               JE   L
     TAC: goto L          →   JMP  L
     TAC: print x         →   PUSH x
                               CALL print
                               POP

   Registers: R0 (accumulator), R1, R2 (scratch)
   ============================================================ */

#ifndef CODEGEN_H
#define CODEGEN_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Reuse the TAC lines loaded by optimizer */
extern char tac_lines[2048][256];
extern int  tac_line_count;

/* ── trim_spaces ─────────────────────────────────────────── */
static inline char* trim(char *s) {
    while (*s == ' ' || *s == '\t') s++;
    int len = strlen(s);
    while (len > 0 && (s[len-1] == ' ' || s[len-1] == '\t')) {
        s[--len] = '\0';
    }
    return s;
}

/* ── split_at ─────────────────────────────────────────────── */
/*    Split string at first occurrence of sep, put parts in L/R */
static inline int split_at(const char *src, char sep,
                            char *left, int lsize,
                            char *right, int rsize) {
    const char *p = strchr(src, sep);
    if (!p) return 0;
    int n = p - src;
    if (n >= lsize) n = lsize - 1;
    strncpy(left, src, n); left[n] = '\0';
    strncpy(right, p + 1, rsize - 1); right[rsize-1] = '\0';
    /* trim both */
    char *l2 = trim(left), *r2 = trim(right);
    if (l2 != left) memmove(left, l2, strlen(l2)+1);
    if (r2 != right) memmove(right, r2, strlen(r2)+1);
    return 1;
}

/* ── generate_asm ─────────────────────────────────────────── */
static inline void generate_asm(FILE *out) {
    if (!out) return;

    fprintf(out, "; ══════════════════════════════════════════\n");
    fprintf(out, "; Target Code (Pseudo-Assembly)\n");
    fprintf(out, "; Generated by MiniC Compiler\n");
    fprintf(out, "; ══════════════════════════════════════════\n");
    fprintf(out, ".data\n");
    fprintf(out, ".code\n");
    fprintf(out, "MAIN:\n\n");

    for (int i = 0; i < tac_line_count; i++) {
        char line[256];
        strncpy(line, tac_lines[i], 255);
        char *l = trim(line);

        /* Skip comments and empty lines */
        if (l[0] == ';' || l[0] == '\0') {
            fprintf(out, "%s\n", l[0] ? l : "");
            continue;
        }

        /* Label definition  "Lx:" */
        int len = strlen(l);
        if (l[len-1] == ':') {
            fprintf(out, "\n%s\n", l);
            continue;
        }

        /* goto L */
        if (strncmp(l, "goto ", 5) == 0) {
            fprintf(out, "  JMP  %s\n", l + 5);
            continue;
        }

        /* ifFalse t goto L */
        if (strncmp(l, "ifFalse ", 8) == 0) {
            char cond[64], rest[128];
            /* "ifFalse <cond> goto <label>" */
            sscanf(l + 8, "%63s goto %127s", cond, rest);
            fprintf(out, "  CMP  %s, 0\n", cond);
            fprintf(out, "  JE   %s\n", rest);
            continue;
        }

        /* print x */
        if (strncmp(l, "print ", 6) == 0) {
            fprintf(out, "  PUSH %s\n", l + 6);
            fprintf(out, "  CALL print\n");
            fprintf(out, "  POP  R0\n");
            continue;
        }

        /* Assignment:  lhs = rhs */
        char lhs[64], rhs[192];
        if (split_at(l, '=', lhs, 64, rhs, 192)) {
            char *r = trim(rhs);

            /* Check for binary operation in rhs: a OP b */
            char left_op[64], right_op[64];
            char op_sym = 0;
            const char *ops = "+-*/";
            for (const char *op = ops; *op; op++) {
                /* avoid matching '-' in negative numbers */
                const char *p = strchr(r, *op);
                if (p && p != r) {
                    op_sym = *op;
                    int ln = p - r;
                    strncpy(left_op, r, ln); left_op[ln] = '\0';
                    strcpy(right_op, p + 1);
                    char *lo = trim(left_op), *ro = trim(right_op);
                    if (lo != left_op) memmove(left_op, lo, strlen(lo)+1);
                    if (ro != right_op) memmove(right_op, ro, strlen(ro)+1);
                    break;
                }
            }

            if (op_sym) {
                const char *instr =
                    op_sym == '+' ? "ADD" :
                    op_sym == '-' ? "SUB" :
                    op_sym == '*' ? "MUL" : "DIV";
                fprintf(out, "  MOV  R0, %s\n", left_op);
                fprintf(out, "  %s  R0, %s\n", instr, right_op);
                fprintf(out, "  MOV  %s, R0\n", lhs);
            } else if (strncmp(r, "-", 1) == 0) {
                /* Unary negation */
                fprintf(out, "  MOV  R0, %s\n", r + 1);
                fprintf(out, "  NEG  R0\n");
                fprintf(out, "  MOV  %s, R0\n", lhs);
            } else {
                /* Simple copy */
                fprintf(out, "  MOV  %s, %s\n", lhs, r);
            }
            continue;
        }

        /* Fallthrough — emit as comment */
        fprintf(out, "  ; %s\n", l);
    }

    fprintf(out, "\n  HALT\n");
    fprintf(out, "\nEND MAIN\n");
}

#endif /* CODEGEN_H */
